// Liste des principales banques françaises (grand public + en ligne + régionales)
export const FRENCH_BANKS: string[] = [
  "BNP Paribas",
  "Crédit Agricole",
  "Société Générale",
  "LCL",
  "Crédit Mutuel",
  "CIC",
  "Caisse d'Épargne",
  "Banque Populaire",
  "La Banque Postale",
  "HSBC France",
  "Boursorama Banque",
  "Fortuneo",
  "Hello bank!",
  "Monabanq",
  "BforBank",
  "ING France",
  "N26",
  "Revolut",
  "Nickel",
  "Orange Bank",
  "Ma French Bank",
  "Qonto",
  "Shine",
  "Anytime",
  "Bunq",
  "Wise",
  "Lydia",
  "Milleis Banque",
  "Banque Palatine",
  "Banque Courtois",
  "Banque Rhône-Alpes",
  "Banque de Savoie",
  "Banque Tarneaud",
  "Banque Chaix",
  "Banque Kolb",
  "Banque Laydernier",
  "Banque Nuger",
  "Crédit Coopératif",
  "Crédit du Nord",
  "Crédit Municipal",
  "Crédit Foncier",
  "AXA Banque",
  "Allianz Banque",
  "Groupama Banque",
  "Cetelem",
  "Cofidis",
  "Oney Bank",
  "Arkéa",
  "Crédit Mutuel de Bretagne",
  "Crédit Mutuel Océan",
  "Crédit Mutuel Sud-Ouest",
  "Crédit Mutuel du Massif Central",
];
