import type { Member } from "./members.functions";
import type { Chantier } from "./chantier-types";
import type { ChantierTask } from "./chantier-types";
import type { ExpenseRow } from "./expenses.functions";

export const MOCK_MEMBERS: Member[] = [
  {
    id: "m1",
    firstName: "Alain",
    lastName: "Bretillot",
    iban: "FR7630004000031234567890143",
    bankName: "BNP Paribas",
    birthday: "1982-04-12",
    email: "alain@fief.fr",
    spouseFirstName: "Claire",
    spouseLastName: "Bretillot",
  },
  {
    id: "m2",
    firstName: "Marie",
    lastName: "Dupont",
    iban: "FR7614508711234567890",
    bankName: "Crédit Agricole",
    birthday: "1979-08-03",
    email: "marie.dupont@gmail.com",
    spouseFirstName: "Pierre",
    spouseLastName: "Dupont",
  },
  {
    id: "m3",
    firstName: "Pierre",
    lastName: "Dupont",
    iban: "FR7614508711234567891",
    bankName: "Crédit Agricole",
    birthday: "1977-02-17",
    email: "pierre.dupont@gmail.com",
    spouseFirstName: "Marie",
    spouseLastName: "Dupont",
  },
  {
    id: "m4",
    firstName: "Sophie",
    lastName: "Bernard",
    iban: "FR7610096000502788123456",
    bankName: "LCL",
    birthday: "1985-11-28",
    email: "sophie.bernard@yahoo.fr",
    spouseFirstName: "Paul",
    spouseLastName: "Bernard",
  },
  {
    id: "m5",
    firstName: "Paul",
    lastName: "Bernard",
    iban: "FR7610096000502788654321",
    bankName: "LCL",
    birthday: "1983-06-14",
    email: "paul.bernard@yahoo.fr",
    spouseFirstName: "Sophie",
    spouseLastName: "Bernard",
  },
  {
    id: "m6",
    firstName: "Camille",
    lastName: "Leroy",
    iban: "FR7617569000703456789012",
    bankName: "Société Générale",
    birthday: "1990-03-21",
    email: "camille.leroy@outlook.fr",
    spouseFirstName: "",
    spouseLastName: "",
  },
  {
    id: "m7",
    firstName: "Thomas",
    lastName: "Moreau",
    iban: "FR7630066100410001057380016",
    bankName: "CIC",
    birthday: "1975-09-07",
    email: "thomas.moreau@gmail.com",
    spouseFirstName: "Julie",
    spouseLastName: "Moreau",
  },
  {
    id: "m8",
    firstName: "Julie",
    lastName: "Moreau",
    iban: "FR7630066100410001057380099",
    bankName: "CIC",
    birthday: "1978-12-30",
    email: "julie.moreau@gmail.com",
    spouseFirstName: "Thomas",
    spouseLastName: "Moreau",
  },
  {
    id: "m9",
    firstName: "Lucas",
    lastName: "Petit",
    iban: "FR7620041010050500013M02606",
    bankName: "La Banque Postale",
    birthday: "1993-05-16",
    email: "lucas.petit@gmail.com",
    spouseFirstName: "",
    spouseLastName: "",
  },
  {
    id: "m10",
    firstName: "Emma",
    lastName: "Girard",
    iban: "FR7618206004320000156789043",
    bankName: "Crédit Mutuel",
    birthday: "1988-07-09",
    email: "emma.girard@gmail.com",
    spouseFirstName: "",
    spouseLastName: "",
  },
  {
    id: "m11",
    firstName: "Antoine",
    lastName: "Simon",
    iban: "FR7613807008043123456789",
    bankName: "Caisse d'Épargne",
    birthday: "1971-01-25",
    email: "antoine.simon@orange.fr",
    spouseFirstName: "Hélène",
    spouseLastName: "Simon",
  },
  {
    id: "m12",
    firstName: "Hélène",
    lastName: "Simon",
    iban: "FR7613807008043987654321",
    bankName: "Caisse d'Épargne",
    birthday: "1973-10-11",
    email: "helene.simon@orange.fr",
    spouseFirstName: "Antoine",
    spouseLastName: "Simon",
  },
];

export const MOCK_CHANTIERS: Chantier[] = [
  {
    id: "ch00",
    createdAt: "2025-10-01T09:00:00Z",
    reservedBy: "Antoine Simon",
    startDate: "2025-11-08",
    endDate: "2025-11-11",
    startPeriod: "soir",
    endPeriod: "apres_midi",
    adults: 14,
    children: 4,
    calendarEventId: "mock_event_0",
    cancelledAt: null,
  },
  {
    id: "ch01",
    createdAt: "2026-02-10T10:00:00Z",
    reservedBy: "Marie Dupont",
    startDate: "2026-04-04",
    endDate: "2026-04-07",
    startPeriod: "soir",
    endPeriod: "apres_midi",
    adults: 10,
    children: 3,
    calendarEventId: "mock_event_1",
    cancelledAt: null,
  },
  {
    id: "ch02",
    createdAt: "2026-05-20T14:00:00Z",
    reservedBy: "Thomas Moreau",
    startDate: "2026-08-01",
    endDate: "2026-08-04",
    startPeriod: "soir",
    endPeriod: "apres_midi",
    adults: 16,
    children: 6,
    calendarEventId: "mock_event_2",
    cancelledAt: null,
  },
  {
    id: "ch03",
    createdAt: "2026-06-15T11:00:00Z",
    reservedBy: "Alain Bretillot",
    startDate: "2026-09-12",
    endDate: "2026-09-15",
    startPeriod: "soir",
    endPeriod: "apres_midi",
    adults: 12,
    children: 5,
    calendarEventId: "mock_event_3",
    cancelledAt: null,
  },
  {
    id: "ch04",
    createdAt: "2026-04-15T09:00:00Z",
    reservedBy: "Sophie Bernard",
    startDate: "2026-10-24",
    endDate: "2026-11-01",
    startPeriod: "",
    endPeriod: "",
    adults: 18,
    children: 7,
    calendarEventId: "mock_event_4",
    cancelledAt: null,
  },
];

export const MOCK_TASKS: Record<string, ChantierTask[]> = {
  ch00: [
    {
      id: "t01",
      label: "Tonte de la pelouse principale",
      done: true,
      note: "Fait en 2h30, herbe très haute après l'été",
      participants: "Antoine, Thomas, Lucas",
      completedAt: "2025-11-09T14:00:00Z",
      resultPhotoUrl: "",
      durationMinutes: 150,
      peopleCount: 3,
      urgency: "",
    },
    {
      id: "t02",
      label: "Nettoyage gouttières maison",
      done: true,
      note: "RAS, gouttières propres",
      participants: "Pierre, Paul",
      completedAt: "2025-11-09T16:00:00Z",
      resultPhotoUrl: "",
      durationMinutes: 90,
      peopleCount: 2,
      urgency: "",
    },
    {
      id: "t03",
      label: "Taille des haies du parc",
      done: true,
      note: "",
      participants: "Antoine, Marie, Emma",
      completedAt: "2025-11-10T11:00:00Z",
      resultPhotoUrl: "",
      durationMinutes: 240,
      peopleCount: 3,
      urgency: "",
    },
    {
      id: "t04",
      label: "Réparation clôture nord — section abattue par la tempête",
      done: false,
      note: "3 poteaux à remplacer, acheter du bois 8x8 + fil de fer barbelé",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "tres_urgent",
    },
    {
      id: "t05",
      label: "Vider et nettoyer la cave Nanou",
      done: false,
      note: "",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "urgent",
    },
  ],
  ch01: [
    {
      id: "t10",
      label: "Débroussaillage allée d'entrée",
      done: true,
      note: "Allée propre, branchages évacués",
      participants: "Pierre, Thomas, Lucas",
      completedAt: "2026-04-05T15:00:00Z",
      resultPhotoUrl: "",
      durationMinutes: 180,
      peopleCount: 3,
      urgency: "",
    },
    {
      id: "t11",
      label: "Peinture volets cuisine et séjour",
      done: true,
      note: "2 couches gris anthracite, résultat nickel",
      participants: "Marie, Sophie, Camille",
      completedAt: "2026-04-06T17:00:00Z",
      resultPhotoUrl: "",
      durationMinutes: 300,
      peopleCount: 3,
      urgency: "",
    },
    {
      id: "t12",
      label: "Réparation clôture nord",
      done: true,
      note: "Poteaux remplacés, clôture solide",
      participants: "Paul, Antoine, Lucas",
      completedAt: "2026-04-05T12:00:00Z",
      resultPhotoUrl: "",
      durationMinutes: 210,
      peopleCount: 3,
      urgency: "tres_urgent",
    },
    {
      id: "t13",
      label: "Vider et nettoyer la cave Nanou",
      done: true,
      note: "4 sacs poubelle, 2 caisses gardées",
      participants: "Emma, Hélène, Julie",
      completedAt: "2026-04-06T11:00:00Z",
      resultPhotoUrl: "",
      durationMinutes: 120,
      peopleCount: 3,
      urgency: "urgent",
    },
    {
      id: "t14",
      label: "Révision chaudière — vérifier brûleur et joints",
      done: false,
      note: "Contacter chauffagiste avant le chantier pour intervention sur place",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "tres_urgent",
    },
    {
      id: "t15",
      label: "Remplacer carrelage salle de bain Émile (3 carreaux fissurés)",
      done: false,
      note: "Carreaux 20x20 blanc, trouver les mêmes en quincaillerie",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "urgent",
    },
  ],
  ch02: [
    {
      id: "t20",
      label: "Grand nettoyage terrasse et salon de jardin",
      done: false,
      note: "",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 120,
      peopleCount: 3,
      urgency: "urgent",
    },
    {
      id: "t21",
      label: "Vidange fosse septique",
      done: false,
      note: "Camion à prévoir, contacter SAUR avant le WE",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 60,
      peopleCount: 1,
      urgency: "tres_urgent",
    },
    {
      id: "t22",
      label: "Réparer serrure portail Nanou (coincée depuis mars)",
      done: false,
      note: "",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 30,
      peopleCount: 1,
      urgency: "tres_urgent",
    },
    {
      id: "t23",
      label: "Peindre façade grange côté nord",
      done: false,
      note: "Peinture pierre blanche, environ 40m². Prévoir échafaudage.",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 480,
      peopleCount: 4,
      urgency: "urgent",
    },
    {
      id: "t24",
      label: "Tonte pelouse + ramassage feuilles verger",
      done: false,
      note: "",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 90,
      peopleCount: 2,
      urgency: "",
    },
    {
      id: "t25",
      label: "Installer nouvelle boîte aux lettres (ancienne rouillée)",
      done: false,
      note: "Modèle 2 cases commandé sur Amazon — vérifier livraison avant le WE",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "important",
    },
    {
      id: "t26",
      label: "Révision chaudière",
      done: false,
      note: "Report du chantier d'avril",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 180,
      peopleCount: 1,
      urgency: "tres_urgent",
    },
  ],
  ch03: [
    {
      id: "t30",
      label: "Élagage arbres verger",
      done: false,
      note: "Prévoir scie égoïne + tronçonneuse",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "urgent",
    },
    {
      id: "t31",
      label: "Remplacer carrelage salle de bain Émile",
      done: false,
      note: "Report du chantier d'avril",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "urgent",
    },
    {
      id: "t32",
      label: "Installer poêle à bois dans le salon Nanou",
      done: false,
      note: "Devis accepté, poêle livré en entrepôt — prévoir 1 journée avec ramoneur",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "tres_urgent",
    },
    {
      id: "t33",
      label: "Créer sentier entre Nanou et l'Écurie (30m de gravier)",
      done: false,
      note: "Gravier 20/40mm à commander, 3t environ",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "important",
    },
  ],
  ch04: [
    {
      id: "t40",
      label: "Remise en état piscine pour l'hiver (bâchage, traitement, hivernage)",
      done: false,
      note: "Produits hivernage à acheter chez Irrijardin",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "tres_urgent",
    },
    {
      id: "t41",
      label: "Élagage arbres verger",
      done: false,
      note: "Priorité aux pommiers et poiriers",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "urgent",
    },
    {
      id: "t42",
      label: "Installer poêle à bois — Nanou",
      done: false,
      note: "Report des chantiers précédents",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "tres_urgent",
    },
    {
      id: "t43",
      label: "Créer sentier Nanou ↔ Écurie",
      done: false,
      note: "Gravier à commander",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "important",
    },
    {
      id: "t44",
      label: "Réparer toiture écurie (tuiles cassées côté ouest)",
      done: false,
      note: "Prévoir tuile plate 17x27 couleur vieille France, environ 80 pièces",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "tres_urgent",
    },
    {
      id: "t45",
      label: "Poser isolation combles maison principale (laine de roche)",
      done: false,
      note: "Devis Isover accepté, livraison à planifier",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "urgent",
    },
    {
      id: "t46",
      label: "Créer potager côté Émile (bacs surélevés)",
      done: false,
      note: "4 bacs 120x80 en bois, terreau + géotextile",
      participants: "",
      completedAt: "",
      resultPhotoUrl: "",
      durationMinutes: 0,
      peopleCount: 0,
      urgency: "important",
    },
  ],
};

export const MOCK_EXPENSES: ExpenseRow[] = [
  {
    id: "exp1",
    timestamp: "2026-06-28T10:00:00Z",
    supplier: "Leroy Merlin",
    invoiceDate: "2026-06-28",
    amountTTC: 312.8,
    category: "Entretien & Travaux — Maison et Parc",
    place: "Parc",
    paidBy: "Membre",
    memberName: "Pierre Dupont",
    reimbursementStatus: "À rembourser",
    finalSide: "SCI",
    fileLink: "",
    depositor: "Pierre Dupont",
  },
  {
    id: "exp2",
    timestamp: "2026-06-15T09:00:00Z",
    supplier: "EDF",
    invoiceDate: "2026-06-01",
    amountTTC: 284.5,
    category: "Charges fixes & Administratif — Impôts, assurances, énergie…",
    place: "Maison",
    paidBy: "SCI",
    memberName: "",
    reimbursementStatus: "",
    finalSide: "SCI",
    fileLink: "",
    depositor: "Alain Bretillot",
  },
  {
    id: "exp3",
    timestamp: "2026-06-10T11:00:00Z",
    supplier: "Intermarché Châteauneuf",
    invoiceDate: "2026-06-10",
    amountTTC: 147.6,
    category: "Repas chantier",
    place: "Commun",
    paidBy: "Association",
    memberName: "",
    reimbursementStatus: "",
    finalSide: "Association",
    fileLink: "",
    depositor: "Sophie Bernard",
  },
  {
    id: "exp4",
    timestamp: "2026-05-22T14:00:00Z",
    supplier: "Brico Dépôt",
    invoiceDate: "2026-05-22",
    amountTTC: 89.9,
    category: "Entretien & Travaux — Maison et Parc",
    place: "Nanou",
    paidBy: "Membre",
    memberName: "Thomas Moreau",
    reimbursementStatus: "À rembourser",
    finalSide: "SCI",
    fileLink: "",
    depositor: "Thomas Moreau",
  },
  {
    id: "exp5",
    timestamp: "2026-05-10T08:30:00Z",
    supplier: "AXA Assurances",
    invoiceDate: "2026-05-01",
    amountTTC: 1240.0,
    category: "Charges fixes & Administratif — Impôts, assurances, énergie…",
    place: "Commun",
    paidBy: "SCI",
    memberName: "",
    reimbursementStatus: "",
    finalSide: "SCI",
    fileLink: "",
    depositor: "Alain Bretillot",
  },
  {
    id: "exp6",
    timestamp: "2026-04-30T16:00:00Z",
    supplier: "SAUR",
    invoiceDate: "2026-04-28",
    amountTTC: 540.0,
    category: "Entretien & Travaux — Maison et Parc",
    place: "Commun",
    paidBy: "Membre",
    memberName: "Paul Bernard",
    reimbursementStatus: "Remboursé",
    finalSide: "SCI",
    fileLink: "",
    depositor: "Paul Bernard",
  },
  {
    id: "exp7",
    timestamp: "2026-04-15T10:00:00Z",
    supplier: "Truffaut",
    invoiceDate: "2026-04-14",
    amountTTC: 68.4,
    category: "Vie quotidienne & Accueil — Courses, événements…",
    place: "Parc",
    paidBy: "Membre",
    memberName: "Marie Dupont",
    reimbursementStatus: "À rembourser",
    finalSide: "Association",
    fileLink: "",
    depositor: "Marie Dupont",
  },
  {
    id: "exp8",
    timestamp: "2026-03-20T09:00:00Z",
    supplier: "Enedis",
    invoiceDate: "2026-03-15",
    amountTTC: 196.3,
    category: "Charges fixes & Administratif — Impôts, assurances, énergie…",
    place: "Maison",
    paidBy: "SCI",
    memberName: "",
    reimbursementStatus: "",
    finalSide: "SCI",
    fileLink: "",
    depositor: "Alain Bretillot",
  },
  {
    id: "exp9",
    timestamp: "2026-03-05T15:00:00Z",
    supplier: "Monsieur Bricolage",
    invoiceDate: "2026-03-05",
    amountTTC: 54.2,
    category: "Entretien & Travaux — Maison et Parc",
    place: "Écuries",
    paidBy: "Membre",
    memberName: "Lucas Petit",
    reimbursementStatus: "À rembourser",
    finalSide: "SCI",
    fileLink: "",
    depositor: "Lucas Petit",
  },
  {
    id: "exp10",
    timestamp: "2026-02-18T11:00:00Z",
    supplier: "Lidl Châteauneuf",
    invoiceDate: "2026-02-18",
    amountTTC: 112.7,
    category: "Repas chantier",
    place: "Commun",
    paidBy: "Association",
    memberName: "",
    reimbursementStatus: "",
    finalSide: "Association",
    fileLink: "",
    depositor: "Camille Leroy",
  },
  {
    id: "exp11",
    timestamp: "2026-01-28T14:00:00Z",
    supplier: "Impôts fonciers 2025",
    invoiceDate: "2026-01-15",
    amountTTC: 3820.0,
    category: "Charges fixes & Administratif — Impôts, assurances, énergie…",
    place: "Commun",
    paidBy: "SCI",
    memberName: "",
    reimbursementStatus: "",
    finalSide: "SCI",
    fileLink: "",
    depositor: "Alain Bretillot",
  },
  {
    id: "exp12",
    timestamp: "2025-11-12T09:00:00Z",
    supplier: "Castorama",
    invoiceDate: "2025-11-12",
    amountTTC: 203.5,
    category: "Entretien & Travaux — Maison et Parc",
    place: "Maison",
    paidBy: "Membre",
    memberName: "Antoine Simon",
    reimbursementStatus: "Remboursé",
    finalSide: "SCI",
    fileLink: "",
    depositor: "Antoine Simon",
  },
];
