/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalerBugRouteImport } from './routes/signaler-bug'
import { Route as SignalerRouteImport } from './routes/signaler'
import { Route as ReglesRouteImport } from './routes/regles'
import { Route as ProposerIdeeRouteImport } from './routes/proposer-idee'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ModifierRouteImport } from './routes/modifier'
import { Route as MesReservationsRouteImport } from './routes/mes-reservations'
import { Route as MesChantiersRouteImport } from './routes/mes-chantiers'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as ChantiersRouteImport } from './routes/chantiers'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChantierIdRouteImport } from './routes/chantier.$id'

const SignalerBugRoute = SignalerBugRouteImport.update({
  id: '/signaler-bug',
  path: '/signaler-bug',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalerRoute = SignalerRouteImport.update({
  id: '/signaler',
  path: '/signaler',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglesRoute = ReglesRouteImport.update({
  id: '/regles',
  path: '/regles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposerIdeeRoute = ProposerIdeeRouteImport.update({
  id: '/proposer-idee',
  path: '/proposer-idee',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ModifierRoute = ModifierRouteImport.update({
  id: '/modifier',
  path: '/modifier',
  getParentRoute: () => rootRouteImport,
} as any)
const MesReservationsRoute = MesReservationsRouteImport.update({
  id: '/mes-reservations',
  path: '/mes-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MesChantiersRoute = MesChantiersRouteImport.update({
  id: '/mes-chantiers',
  path: '/mes-chantiers',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ChantiersRoute = ChantiersRouteImport.update({
  id: '/chantiers',
  path: '/chantiers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChantierIdRoute = ChantierIdRouteImport.update({
  id: '/chantier/$id',
  path: '/chantier/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/chantiers': typeof ChantiersRoute
  '/depenses': typeof DepensesRoute
  '/mes-chantiers': typeof MesChantiersRoute
  '/mes-reservations': typeof MesReservationsRoute
  '/modifier': typeof ModifierRoute
  '/profil': typeof ProfilRoute
  '/proposer-idee': typeof ProposerIdeeRoute
  '/regles': typeof ReglesRoute
  '/signaler': typeof SignalerRoute
  '/signaler-bug': typeof SignalerBugRoute
  '/chantier/$id': typeof ChantierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/chantiers': typeof ChantiersRoute
  '/depenses': typeof DepensesRoute
  '/mes-chantiers': typeof MesChantiersRoute
  '/mes-reservations': typeof MesReservationsRoute
  '/modifier': typeof ModifierRoute
  '/profil': typeof ProfilRoute
  '/proposer-idee': typeof ProposerIdeeRoute
  '/regles': typeof ReglesRoute
  '/signaler': typeof SignalerRoute
  '/signaler-bug': typeof SignalerBugRoute
  '/chantier/$id': typeof ChantierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/chantiers': typeof ChantiersRoute
  '/depenses': typeof DepensesRoute
  '/mes-chantiers': typeof MesChantiersRoute
  '/mes-reservations': typeof MesReservationsRoute
  '/modifier': typeof ModifierRoute
  '/profil': typeof ProfilRoute
  '/proposer-idee': typeof ProposerIdeeRoute
  '/regles': typeof ReglesRoute
  '/signaler': typeof SignalerRoute
  '/signaler-bug': typeof SignalerBugRoute
  '/chantier/$id': typeof ChantierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/chantiers'
    | '/depenses'
    | '/mes-chantiers'
    | '/mes-reservations'
    | '/modifier'
    | '/profil'
    | '/proposer-idee'
    | '/regles'
    | '/signaler'
    | '/signaler-bug'
    | '/chantier/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/chantiers'
    | '/depenses'
    | '/mes-chantiers'
    | '/mes-reservations'
    | '/modifier'
    | '/profil'
    | '/proposer-idee'
    | '/regles'
    | '/signaler'
    | '/signaler-bug'
    | '/chantier/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/chantiers'
    | '/depenses'
    | '/mes-chantiers'
    | '/mes-reservations'
    | '/modifier'
    | '/profil'
    | '/proposer-idee'
    | '/regles'
    | '/signaler'
    | '/signaler-bug'
    | '/chantier/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  ChantiersRoute: typeof ChantiersRoute
  DepensesRoute: typeof DepensesRoute
  MesChantiersRoute: typeof MesChantiersRoute
  MesReservationsRoute: typeof MesReservationsRoute
  ModifierRoute: typeof ModifierRoute
  ProfilRoute: typeof ProfilRoute
  ProposerIdeeRoute: typeof ProposerIdeeRoute
  ReglesRoute: typeof ReglesRoute
  SignalerRoute: typeof SignalerRoute
  SignalerBugRoute: typeof SignalerBugRoute
  ChantierIdRoute: typeof ChantierIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signaler-bug': {
      id: '/signaler-bug'
      path: '/signaler-bug'
      fullPath: '/signaler-bug'
      preLoaderRoute: typeof SignalerBugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaler': {
      id: '/signaler'
      path: '/signaler'
      fullPath: '/signaler'
      preLoaderRoute: typeof SignalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regles': {
      id: '/regles'
      path: '/regles'
      fullPath: '/regles'
      preLoaderRoute: typeof ReglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposer-idee': {
      id: '/proposer-idee'
      path: '/proposer-idee'
      fullPath: '/proposer-idee'
      preLoaderRoute: typeof ProposerIdeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modifier': {
      id: '/modifier'
      path: '/modifier'
      fullPath: '/modifier'
      preLoaderRoute: typeof ModifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-reservations': {
      id: '/mes-reservations'
      path: '/mes-reservations'
      fullPath: '/mes-reservations'
      preLoaderRoute: typeof MesReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-chantiers': {
      id: '/mes-chantiers'
      path: '/mes-chantiers'
      fullPath: '/mes-chantiers'
      preLoaderRoute: typeof MesChantiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chantiers': {
      id: '/chantiers'
      path: '/chantiers'
      fullPath: '/chantiers'
      preLoaderRoute: typeof ChantiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chantier/$id': {
      id: '/chantier/$id'
      path: '/chantier/$id'
      fullPath: '/chantier/$id'
      preLoaderRoute: typeof ChantierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  ChantiersRoute: ChantiersRoute,
  DepensesRoute: DepensesRoute,
  MesChantiersRoute: MesChantiersRoute,
  MesReservationsRoute: MesReservationsRoute,
  ModifierRoute: ModifierRoute,
  ProfilRoute: ProfilRoute,
  ProposerIdeeRoute: ProposerIdeeRoute,
  ReglesRoute: ReglesRoute,
  SignalerRoute: SignalerRoute,
  SignalerBugRoute: SignalerBugRoute,
  ChantierIdRoute: ChantierIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
